version: '3.9'
services:
  web:
    build: .
    container_name: home-hub
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./photos:/photos:ro
      - ./public:/app/public
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    container_name: home-hub-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homehub
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  dbdata: